spring.application.name=order-service

server.port=9020
server.servlet.context-path=/orders

spring.datasource.url=jdbc:postgresql://localhost:5432/orderDB
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka