spring.application.name=inventory-service

server.port=9010
server.servlet.context-path=/inventory

spring.datasource.url=jdbc:postgresql://postgres-inventory:5432/inventoryDB
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka